Name:           ros-kinetic-test-diagnostic-aggregator
Version:        1.9.1
Release:        0%{?dist}
Summary:        ROS test_diagnostic_aggregator package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/test_diagnostic_aggregator
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-diagnostic-aggregator >= 1.8.9
Requires:       ros-kinetic-diagnostic-msgs
Requires:       ros-kinetic-pluginlib
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-rospy
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-diagnostic-aggregator >= 1.8.9
BuildRequires:  ros-kinetic-diagnostic-msgs
BuildRequires:  ros-kinetic-pluginlib
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-rospy
BuildRequires:  ros-kinetic-rostest

%description
Basic diagnostic_aggregator tests are in the

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sat Jul 15 2017 Brice Rebsamen <brice.rebsamen@gmail.com> - 1.9.1-0
- Autogenerated by Bloom

* Tue Apr 25 2017 Brice Rebsamen <brice.rebsamen@gmail.com> - 1.9.0-0
- Autogenerated by Bloom

* Tue Jun 14 2016 Brice Rebsamen <brice.rebsamen@gmail.com> - 1.8.10-0
- Autogenerated by Bloom

* Thu Mar 31 2016 Brice Rebsamen <brice.rebsamen@gmail.com> - 1.8.9-0
- Autogenerated by Bloom

