Name:           ros-jade-test-diagnostic-aggregator
Version:        1.8.10
Release:        0%{?dist}
Summary:        ROS test_diagnostic_aggregator package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/test_diagnostic_aggregator
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-jade-diagnostic-aggregator >= 1.8.9
Requires:       ros-jade-diagnostic-msgs
Requires:       ros-jade-pluginlib
Requires:       ros-jade-roscpp
Requires:       ros-jade-rospy
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-diagnostic-aggregator >= 1.8.9
BuildRequires:  ros-jade-diagnostic-msgs
BuildRequires:  ros-jade-pluginlib
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-rospy
BuildRequires:  ros-jade-rostest

%description
Basic diagnostic_aggregator tests are in the

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Tue Jun 14 2016 Brice Rebsamen <brice.rebsamen@gmail.com> - 1.8.10-0
- Autogenerated by Bloom

* Wed Mar 02 2016 Brice Rebsamen <brice.rebsamen@gmail.com> - 1.8.9-1
- Autogenerated by Bloom

* Wed Mar 02 2016 Brice Rebsamen <brice.rebsamen@gmail.com> - 1.8.9-0
- Autogenerated by Bloom

* Thu Feb 12 2015 Brice Rebsamen <brice.rebsamen@gmail.com> - 1.8.7-0
- Autogenerated by Bloom

